<?php
/*
 * Configuración de las rutas de la API.
 */
$r = '/api/v1';
Router::addRoutes([
  'GET' => [
    "$r/authorizations/:id" => "AuthorizationsController::get",
    "$r/authorizations" => "AuthorizationsController::index",
    "$r/companies/:id" => "CompaniesController::get",
    "$r/companies" => "CompaniesController::index",
    "$r/contacts/:id" => "ContactsController::get",
    "$r/contacts" => "ContactsController::index",
    "$r/farms/:id" => "FarmsController::get",
    "$r/farms" => "FarmsController::index",
    "$r/handlers/:id" => "HandlersController::get",
    "$r/handlers" => "HandlersController::index",
    "$r/items/:id" => "ItemsController::get",
    "$r/items" => "ItemsController::index",
    "$r/members/:id" => "MembersController::get",
    "$r/members" => "MembersController::index",
    "$r/parcels/:id" => "ParcelsController::get",
    "$r/parcels" => "ParcelsController::index",
    "$r/permissions/:id" => "PermissionsController::get",
    "$r/permissions" => "PermissionsController::index",
    "$r/plots/:id" => "PlotsController::get",
    "$r/plots" => "PlotsController::index",
    "$r/products/:id" => "ProductsController::get",
    "$r/products" => "ProductsController::index",
    "$r/profiles/:id" => "ProfilesController::get",
    "$r/profiles" => "ProfilesController::index",
    "$r/properties/:id" => "PropertiesController::get",
    "$r/properties" => "PropertiesController::index",
    "$r/stuffs/:id" => "StuffsController::get",
    "$r/stuffs" => "StuffsController::index",
    "$r/tasks/:id" => "TasksController::get",
    "$r/tasks" => "TasksController::index",
    "$r/taxonomies/:id" => "TaxonomiesController::get",
    "$r/taxonomies" => "TaxonomiesController::index",
    "$r/teams/:id" => "TeamsController::get",
    "$r/teams" => "TeamsController::index",
    "$r/users/:id" => "UsersController::get",
    "$r/users" => "UsersController::index",
    "$r/varieties/:id" => "VarietiesController::get",
    "$r/varieties" => "VarietiesController::index",
    #"$r/set-default-property/:user_id/:property_id" => 'ApiV1Controller::set_default_property',
  ],
  'POST' => [
    "$r/authorizations/:id" => "AuthorizationsController::post",
    "$r/companies/:id" => "CompaniesController::post",
    "$r/contacts/:id" => "ContactsController::post",
    "$r/farms/:id" => "FarmsController::post",
    "$r/handlers/:id" => "HandlersController::post",
    "$r/items/:id" => "ItemsController::post",
    "$r/members/:id" => "MembersController::post",
    "$r/parcels/:id" => "ParcelsController::post",
    "$r/permissions/:id" => "PermissionsController::post",
    "$r/plots/:id" => "PlotsController::post",
    "$r/products/:id" => "ProductsController::post",
    "$r/profiles/:id" => "ProfilesController::post",
    "$r/properties/:id" => "PropertiesController::post",
    "$r/sessions/login" => "SessionController::login",
    "$r/stuffs/:id" => "StuffsController::post",
    "$r/tasks/:id" => "TasksController::post",
    "$r/taxonomies/:id" => "TaxonomiesController::post",
    "$r/teams/:id" => "TeamsController::post",
    "$r/users/:id" => "UsersController::post",
    "$r/varieties/:id" => "VarietiesController::post",
  ],
]);